version: "3.8"
services:
  solr:
    image: solr:9
    container_name: solr
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/var/solr
    command: solr-precreate code
    networks:
      - solr_net

volumes:
  solr_data:
    name: solr_data

networks:
  solr_net:
    driver: bridge
