version: "3.8"
services:
  solr:
    image: solr:9 # You can specify a different Solr version if needed
    container_name: solr
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/var/solr
    # Optional: Command to create a core on startup
    # command: solr-precreate mycore
    networks:
      - solr_net

volumes:
  solr_data:

networks:
  solr_net:
    driver: bridge
