version: "3.8"
services:
  solr:
    image: solr:9
    container_name: codesearch_solr
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/var/solr
    command: solr-precreate code
    networks:
      - app_net

  redis:
    image: redis:7-alpine
    container_name: codesearch_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - app_net

  worker:
    build: ./worker
    container_name: codesearch_worker
    depends_on:
      - redis
      - solr
    restart: unless-stopped
    environment:
      - REDIS_URL=redis://redis:6379
      - SOLR_HOST=solr
      - SOLR_PORT=8983
      - SOLR_CORE=code
      - SOLR_PATH=/solr
    volumes:
      - worker_tmp:/tmp
    networks:
      - app_net

  frontend:
    build: ./frontend
    container_name: codesearch_frontend
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - solr
      - worker
    restart: unless-stopped
    environment:
      - REDIS_URL=redis://redis:6379
      - SOLR_HOST=solr
      - SOLR_PORT=8983
      - SOLR_CORE=code
      - NODE_ENV=production
    networks:
      - app_net

volumes:
  solr_data:
    name: solr_data
  redis_data:
    name: redis_data
  worker_tmp:
    name: worker_tmp

networks:
  app_net:
    driver: bridge
